env:
  es2021: true
  node: true
extends: airbnb-base
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: 
  no-console: 0
  import/extensions:
    - error
    - ignorePackages
    - js: always
  linebreak-style: 0
runs:
  using: 'node20'
  main: 'index.js'
  post: 'cleanup.js'
  pre: 'cleanup.js'
  pre-if: runner.os == 'linux'
